<?php

/**
 * @file
 * Contains event_registration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function event_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.event_registration':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Event Registration module allows users to register for events.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_mail().
 */
function event_registration_mail($key, &$message, $params) {
  switch ($key) {
    case 'registration_confirmation':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;

    case 'admin_notification':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}